name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.1

    - name: Install dependencies
      run: go mod tidy

    - name: Build
      run: make build

    - name: Test
      env:
        AFRRICAS_TALKING_SANDBOX_API_KEY: ${{ secrets.AFRRICAS_TALKING_SANDBOX_API_KEY }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_USER: ${{ secrets.DB_USER }}
        SHORT_CODE: ${{ secrets.SHORT_CODE }}
        SMS_PROVIDER_USERNAME: ${{ secrets.SMS_PROVIDER_USERNAME }}
      run: go test -v ./tests