name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.1

    - name: Install dependencies
      run: go mod tidy

    - name: Build
      run: make build

    - name: Wait for PostgreSQL to be ready
      run: |
        while ! pg_isready -h localhost -p 5432 -U ${{ secrets.DB_USER }}; do
          echo "Waiting for PostgreSQL..."
          sleep 1
        done

    - name: Create database
      run: |
        psql -h localhost -U ${{ secrets.DB_USER }} -c "CREATE DATABASE ${{ secrets.DB_NAME }};" postgres
      env:
        PGPASSWORD: ${{ secrets.DB_PASSWORD }}

    - name: Run Tests
      env:
        AFRRICAS_TALKING_SANDBOX_API_KEY: ${{ secrets.AFRRICAS_TALKING_SANDBOX_API_KEY }}
        DB_HOST: localhost
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_PORT: 5432
        DB_USER: ${{ secrets.DB_USER }}
        SHORT_CODE: ${{ secrets.SHORT_CODE }}
        SMS_PROVIDER_USERNAME: ${{ secrets.SMS_PROVIDER_USERNAME }}
      run: go test -v ./tests
